require:
- rubocop-rake
- rubocop-rspec

Layout/LineLength:
  Max: 100

AllCops:
  Exclude:
  - 'db/schema.rb'
  - 'vendor/**/*'
  TargetRubyVersion: 3.1
  NewCops: enable

Metrics/AbcSize:
  Max: 21

Metrics/BlockLength:
  Max: 35
  Exclude:
  - 'spec/**/*_spec.rb'
  - 'Rakefile'
  - '*.gemspec'

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 160
  Exclude:
  - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  Max: 300
  Exclude:
  - 'spec/**/*_spec.rb'

Metrics/ParameterLists:
  Max: 6

Gemspec/RequireMFA:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Style/MixinUsage:
  Exclude:
  - "bin/console"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringConcatenation:
  Exclude:
  - 'Rakefile'

RSpec/ExampleLength:
  Max: 10

RSpecRails:
  Enabled: false
