name: Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      ## Here's the new step for release-please
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.AUTO_RELEASE_TOKEN }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          bundler-cache: true
          ruby-version: .ruby-version

      - uses: rubygems/release-gem@v1
        if: ${{ steps.release.outputs.release_created }}
